<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="ConcreteObject" Id="{9a968a31-5cce-4a3e-b3fb-8572d9791703}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ConcreteObject EXTENDS CNM_AbstractObject.Object
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="className" Id="{a0a3848f-4547-4282-87e2-2251efa39435}">
      <Declaration><![CDATA[PROPERTY className :CNM_AbstractObject.ClassName]]></Declaration>
      <Get Name="Get" Id="{5efe1734-dad0-4157-88c9-aecbc913a7d1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[className := 'ConcreteObject';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="ConcreteObject">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="ConcreteObject.className.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>